### ISSUE TITLE
大佬，你好，请问一下cookie相关

### ISSUE THREAD

**Issue by AndoKaguya** [shenmishajing-script/wyycg_checkin#2]
大佬，你好，请问一下cookie怎么获取，截取哪部分填入config呢？

**Comment by shenmishajing** [comment]
去网易云游戏页面打开开发者工具，刷新一下，能看到sign-info和sign-user-info的request，在里面找找有的request带有Authorization字段，把那个复制过来就可以了。

![截屏2021-10-09 09 41 27](https://user-images.githubusercontent.com/32559715/136639499-a73ba30b-0aa2-4754-b5ce-f6e8057bf94a.png)

**Comment by AndoKaguya** [comment]
> 去网易云游戏页面打开开发者工具，刷新一下，能看到sign-info和sign-user-info的request，在里面找找有的request带有Authorization字段，把那个复制过来就可以了。
> 
> ![截屏2021-10-09 09 41 27](https://user-images.githubusercontent.com/32559715/136639499-a73ba30b-0aa2-4754-b5ce-f6e8057bf94a.png)

谢谢！
